In [3]:
a,b='var1', 'var2'

In [4]:
a,b

('var1', 'var2')

In [5]:
a

'var1'

In [6]:
a=100
b=3.14
c=True

In [7]:
print("a의 값은?", a)
print("a의 데이터 변수 형태는?:", type(a))
print("b의 값은?", b)
print("b의 데이터 변수 형태는?:", type(b))
print("c의 값은?", c)
print("c의 데이터 변수 형태는?:", type(c))

a의 값은? 100
a의 데이터 변수 형태는?: <class 'int'>
b의 값은? 3.14
b의 데이터 변수 형태는?: <class 'float'>
c의 값은? True
c의 데이터 변수 형태는?: <class 'bool'>


In [3]:
a = True

In [5]:
type(a)

bool

In [21]:
sentence = '안녕하세요.' + ' ' +  "반갑습니다."

In [22]:
sentence

'안녕하세요. 반갑습니다.'

In [23]:
sentence.split()

['안녕하세요.', '반갑습니다.']

In [27]:
sentence.find('반갑습니다.')


7

In [28]:
sentence.find('python')

-1

In [29]:
sentence.replace('.','!')

'안녕하세요! 반갑습니다!'

In [31]:
sentence.strip('안녕')

'하세요. 반갑습니다.'

In [41]:
data =[10,20,30,40,50,60] #data를 list형태로 생성

In [33]:
print(data)
type(data)

[10, 20, 30, 40, 50, 60]


list

In [42]:
print(data[0])
print(data[4])

10
50


In [43]:
data[0]=data[4]
print(data)

[50, 20, 30, 40, 50, 60]


In [45]:
data = ["사과", "배", "포도", "딸기", "토마토", "메론"]
print(data[0])

사과


In [46]:
print(data[2:4])

['포도', '딸기']


In [48]:
data_1 = [10, 20, 30, 40, 50]
data_2 = [5, 10, 15, 20, 25]

In [49]:
data_1 + data_2

[10, 20, 30, 40, 50, 5, 10, 15, 20, 25]

In [57]:
lists = [1, 100, 'python']
print(lists)
print(type(lists))

[1, 100, 'python']
<class 'list'>


In [58]:
lists.append('py')
print(lists)

[1, 100, 'python', 'py']


In [59]:
lists.insert(1,'0.5')
print(lists)

[1, '0.5', 100, 'python', 'py']


In [60]:
lists.remove('python')
print(lists)

[1, '0.5', 100, 'py']


In [64]:
data_list = [10, 20, 30, 40, 50, 60, 70]

print("최소값: ". min(data_list)) 

print("최소값: ", min(data_list))
print("최대값: ", max(data_list))

In [68]:
data_list = [50, 20, 40, 30, 60, 90]

In [71]:
data_list.sort()
print(data_list)

[20, 30, 40, 50, 60, 90]


In [72]:
p = 1  + 2

In [76]:
# tuple: 한번 값이 항목되면 변경이 불가함
data = ("사과", "배", "포도", "토마토", "딸기")

print(data)
print(type(data))

('사과', '배', '포도', '토마토', '딸기')
<class 'tuple'>


In [78]:
data[0] = 100

TypeError: 'tuple' object does not support item assignment

In [87]:
data = (100, 200, 100, 300, 100, 500)
print(type(data))
print(data.count(100))

<class 'tuple'>
3


In [90]:
print(data[2:4])

(100, 300)


In [92]:
data1 = ("사과", "배", "포도", "토마토", "딸기")
data2 = (100, 200, 300, 400, 500)
data = data1 + data2
print(data)

('사과', '배', '포도', '토마토', '딸기', 100, 200, 300, 400, 500)


In [94]:
#튜플 반복
print(data*2)

('사과', '배', '포도', '토마토', '딸기', 100, 200, 300, 400, 500, '사과', '배', '포도', '토마토', '딸기', 100, 200, 300, 400, 500)


In [97]:
#set: 항목의 순서가 없음, 중복이 없음, 추가가 가능, 인덱스와 연산이 불가능
data = {100, 200, 300}
print(type(data))

<class 'set'>


In [99]:
data = {100, 200, 300, 400, 500, 600}
print(data)
data.add(700)
print(data)

{100, 200, 300, 400, 500, 600}
{100, 200, 300, 400, 500, 600, 700}


In [105]:
data = {100}
print("여러 데이터를 추가하기 전")
print(data)

print()

여러 데이터를 추가하기 전
{100}



In [110]:
data.update([200, 300, 400, 500, 600])
print("여러 개의 데이터를 추가한 후")
print(data)

여러 개의 데이터를 추가한 후
{100, 200, 300, 400, 500, 600}


In [113]:
data = {100, 200, 300, 400, 500, 600}
print("데이터를 삭제하기 전")
print(data)
# 세트 자료구조에서 remove를 이용하여 데이터를 제거
data.remove(600)

print("데이터를 삭제한 후")
print(data)

데이터를 삭제하기 전
{100, 200, 300, 400, 500, 600}
데이터를 삭제한 후
{100, 200, 300, 400, 500}


In [115]:
#데이터 초기화
data = {100, 200, 300, 400, 500 ,600}
print("데이터를 삭제하기 전")
print(data)

print()
# 세트 자료구조에서 clear를 이용하여 전체 데이터를  초기화
data.clear()
print(data)

데이터를 삭제하기 전
{100, 200, 300, 400, 500, 600}

set()


In [131]:
# 세트 교집합
A = {100, 200, 300, 400, 500}
B = {100, 150, 200, 250, 300}
print(A)
print(type(A))
print(B)
print(type(B))
print()
#intersection함수는 교집합을 나타내는 함수
print("intersection은 교집합을 나타내는 함수")
print(A.intersection(B))
print(B.intersection(A))

{100, 200, 300, 400, 500}
<class 'set'>
{100, 200, 300, 150, 250}
<class 'set'>

intersection은 교집합을 나타내는 함수
{200, 100, 300}
{200, 100, 300}


In [129]:
# 세트 차집합
A = {100, 200, 300, 400, 500}
B = {100, 150, 200, 250, 300}
print(A)
print(type(A))
print(B)
print(type(B))
print()
#differnce는 차집합을 나타내는 함수
print("difference는 차집합을 나타내는 함수")
print('A: ', A.difference(B))
print("B: " , B.difference(A))

{100, 200, 300, 400, 500}
<class 'set'>
{100, 200, 300, 150, 250}
<class 'set'>

difference는 차집합을 나타내는 함수
A:  {400, 500}
B:  {250, 150}


In [132]:
# 세트 합집합
A = {100, 200, 300, 400, 500}
B = {100, 150, 200, 250, 300}
print(A)
print(type(A))
print(B)
print(type(B))
print()
# union은 합집합을 나타내는 함수
print("union은 합집합을 나타내는 함수")
print(A.union(B))

{100, 200, 300, 400, 500}
<class 'set'>
{100, 200, 300, 150, 250}
<class 'set'>

union은 합집합을 나타내는 함수
{100, 200, 300, 400, 500, 150, 250}


In [142]:
# 합집합 - 교집합
A = {100, 200, 300, 400, 500}
B = {100, 150, 200, 250, 300}
print(A)
print(type(A))
print(B)
print(type(B))
print()

print("합집합: ", A.union(B))
print("교집합: ", A.intersection(B))
print()

print("symmetric_difference함수는 합집합에서 교집합을 뺀 나머지 집합을 나타내는 함수")
print(A.symmetric_difference(B))

{100, 200, 300, 400, 500}
<class 'set'>
{100, 200, 300, 150, 250}
<class 'set'>

합집합:  {100, 200, 300, 400, 500, 150, 250}
교집합:  {200, 100, 300}

symmetric_difference함수는 합집합에서 교집합을 뺀 나머지 집합을 나타내는 함수
{400, 500, 150, 250}


In [153]:
#딕셔너리(dictionary)의 기본 구조는 다음과 같이 표현할 수 있음
data = {"사과": 300, "배":200, "포도":500, "딸기":700 }
print(type(data))

<class 'dict'>


In [149]:
print(data["사과"])
print(data.get("사과"))

300
300


In [162]:
data = {"사과": 300, "배":200, "포도":500, "딸기":700 }
print("딕셔너리에 추가하기 전체 데이터")
print(data)

print()

#딕셔너리에 데이터를 추가할 때는 아래와 같이 키를 설정하고 값을 입력함
data['메론'] = 1000
print("딕셔너리에 추가한 후 전체 데이터")
print(data)

딕셔너리에 추가하기 전체 데이터
{'사과': 300, '배': 200, '포도': 500, '딸기': 700}

딕셔너리에 추가한 후 전체 데이터
{'사과': 300, '배': 200, '포도': 500, '딸기': 700, '메론': 1000}


In [164]:
#딕셔너리 데이터 예제를 data변수에 입력
data = {"사과": 300, "배":200, "포도":500, "딸기":700 }
print("딕셔너리에 삭제하기 전 전체 데이터")
print(data)

#딕셔너리 pop함수를 이용해 데이터를 삭제 가능
print("딕셔너리에 삭제한 후 전체 데이터")
data.pop("사과")
print(data)


딕셔너리에 삭제하기 전 전체 데이터
{'사과': 300, '배': 200, '포도': 500, '딸기': 700}
딕셔너리에 삭제한 후 전체 데이터
{'배': 200, '포도': 500, '딸기': 700}


In [1]:
data = {"사과": 300, "배":200, "포도":500, "딸기":700 }
print("딕셔너리에 삭제하기 전 전체 데이터")
print(data)

print()
#sorted 정렬시키는 내장함수
print(sorted(data))
print()
# value값을 이용해 정렬하고 싶으면 아래와 같이 실행
print()
print(sorted(data.values()))

딕셔너리에 삭제하기 전 전체 데이터
{'사과': 300, '배': 200, '포도': 500, '딸기': 700}

['딸기', '배', '사과', '포도']


[200, 300, 500, 700]


## 제어문 및 반복문

In [1]:
#if 문 예제 1
a = 100
if a == 100:
    print("일치")
else:
    print("불일치")

일치


In [2]:
#if문 예제2
a = 200
if a == 100:
    print("일치")
else:
    print("불일치")

불일치


In [3]:
#while문 예제1
a = 1

while a <= 5:
    print(a)
    a += 1

1
2
3
4
5


In [4]:
#for문 예제1
num_list = [1, 2, 3, 4, 5]

for num in num_list:
    print(num)

1
2
3
4
5


In [9]:
#함수 예제1
def f(x):
    return x + 10
f(2)

12

In [17]:
#람다의 예제1
def f(x):
    return x + 10
#일반적인 함수를 이용해 함수를 구현
print(f(10))

#lambda를 이용해 함수를 간단하게 구현
print((lambda x: x+10)(10))

20
20


In [19]:
#람다의 예제2
def f(x):
    return x + 10
f(y)

NameError: name 'y' is not defined

## 라이브러리

In [ ]:
#Built-in  함수 중 대표함수인 input과 print
text = input("문장, 단어를 입력하세요.")
print(text)

### numpy, pandas

#### numpy라이브러리

In [1]:
#numpy(numerical python)이란 뜻으로 배열 또는 다양한 자료구조를 다룰 수 있는 
#클래스를 포함하고 있는 패키지

#List 자료형을 이용한 다차원 배열의 예
np =[1.0, 10.4, 3.2, 5.1, 7.5, 2.7]

flotV = [np, np, np]
flotV

[[1.0, 10.4, 3.2, 5.1, 7.5, 2.7],
 [1.0, 10.4, 3.2, 5.1, 7.5, 2.7],
 [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]]

In [3]:
#1차원 배열 값 추출의 예
#flov는 다차원 배열
flotV[0]

[1.0, 10.4, 3.2, 5.1, 7.5, 2.7]

In [6]:
flotV[0] = 'python'
flotV[0]

'python'

In [9]:
import numpy as np
#numpy 패키지를 np라는 명칭으로 축약

a = np.array([1, 2.5, 4.0, 5.5, 7.0])

a[3:]

array([5.5, 7. ])

In [19]:
a.sum()
#np.array로 생성된 변수 a의 합을 출력

20.0

In [17]:
a.std()
#....로 생성된 변수 a의 표준편차를 출력

2.1213203435596424

In [20]:
a.cumsum()
#....로 생성된 변수 a의 누적 합을 출력

array([ 1. ,  3.5,  7.5, 13. , 20. ])

In [22]:
print(a)
print(a*2)
print(a**2)
print(np.sqrt(a))
#변수 a의 값에 2를 루트를 적용한 값을 출력

[1.  2.5 4.  5.5 7. ]
[ 2.  5.  8. 11. 14.]
[ 1.    6.25 16.   30.25 49.  ]
[1.         1.58113883 2.         2.34520788 2.64575131]


In [24]:
#axis 축을 기준으로 합계 표현
b = np.array([a, a**2])
b

array([[ 1.  ,  2.5 ,  4.  ,  5.5 ,  7.  ],
       [ 1.  ,  6.25, 16.  , 30.25, 49.  ]])

In [28]:
print(b.sum(axis=0))
print(b.sum(axis=1))

[ 2.    8.75 20.   35.75 56.  ]
[ 20.  102.5]


In [31]:
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
values = np.zeros((2,3), dtype="l")
values

array([[0, 0, 0],
       [0, 0, 0]])

#### pandas

In [47]:
import pandas as pd
import numpy as np

##### series

In [44]:
pandas_series = pd.Series([3000, 32000, 2700], 
                          index = ['2016-11-10', '2016-11-11', '2016-11-12'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


2016-11-10     3000
2016-11-11    32000
2016-11-12     2700
dtype: int64

In [46]:
pandas_series[1:]

2016-11-11    32000
2016-11-12     2700
dtype: int64

##### Data Frame

In [57]:
df = pd.DataFrame([100, 150, 200, 250, 300], columns = ['numbers'], 
                  index = ['a', 'b', 'c', 'd', 'e'])
df

numbers
a      100
b      150
c      200
d      250
e      300

In [58]:
print(df.index)
print(df.columns)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Index(['numbers'], dtype='object')


In [73]:
df.loc['c']
#df.ix기능은 사용 불가능하여 대체 명령어를 찾음

numbers    200
Name: c, dtype: int64